// src/components/Footer/Footer.tsx
import { useState, useEffect } from "react";
import "./Footer.css";

function Footer() {
  const [isDarkMode, setIsDarkMode] = useState(false);
  const currentYear = new Date().getFullYear();

  const toggleDarkMode = () => {
    setIsDarkMode(!isDarkMode);
    document.body.classList.toggle("dark-mode", !isDarkMode);
    localStorage.setItem("darkMode", String(!isDarkMode));
  };

  useEffect(() => {
    const savedDarkMode = localStorage.getItem("darkMode") === "true";
    // eslint-disable-next-line react-hooks/set-state-in-effect
    setIsDarkMode(savedDarkMode);
    document.body.classList.toggle("dark-mode", savedDarkMode);
  }, []);

  return (
    <footer>
      <div className="footer-content">
        <div className="footer-links">
          <a href="https://www.instagram.com/SalsaSegura" target="_blank" rel="noopener noreferrer">
            📱 Instagram
          </a>
          <a href="mailto:info@SalsaSegura.com">📧 Email</a>
          <a href="tel:+19784440922">📞 Call</a>
        </div>

        <div className="dark-mode-container">
          <button
            className="dark-mode-toggle"
            aria-label={isDarkMode ? "Switch to light mode" : "Switch to dark mode"}
            onClick={toggleDarkMode}
          >
            {isDarkMode ? "☀️" : "🌙"}
          </button>
        </div>

        <div className="copyright">
          &copy; {currentYear} Salsa Segura. All rights reserved. | Passion For Dance
        </div>
      </div>
      <a
        href="https://www.buymeacoffee.com/rseg"
        target="_blank"
        rel="noopener noreferrer"
        style={{ marginTop: "4px" }}
      >
        <img
          src="https://img.buymeacoffee.com/button-api/?text=Buy me a coffee&emoji=☕&slug=rseg&button_colour=059669&font_colour=ffffff&font_family=Poppins&outline_colour=059669&coffee_colour=FFDD00"
          alt="Buy me a coffee"
          style={{ height: "36px", width: "auto", borderRadius: "8px" }}
        />
      </a>
    </footer>
  );
}

export default Footer;

// src/components/Footer.vue
<template>
  <footer>
    <div class="footer-content">
      <div class="footer-links">
        <a
          href="https://www.instagram.com/SalsaSegura"
          target="_blank"
          rel="noopener noreferrer"
        >
          📱 Instagram
        </a>
        <a href="mailto:info@SalsaSegura.com">📧 Email</a>
        <a href="tel:+19784440922">📞 Call</a>
      </div>

      <div class="dark-mode-container">
        <button
          class="dark-mode-toggle"
          :aria-label="isDarkMode ? 'Switch to light mode' : 'Switch to dark mode'"
          @click="toggleDarkMode"
        >
          {{ isDarkMode ? "☀️" : "🌙" }}
        </button>
      </div>

      <div class="copyright">
        &copy; {{ currentYear }} Salsa Segura. All rights reserved. | Passion For
        Dance
      </div>
    </div>
  </footer>
</template>

<script lang="ts">
import { defineComponent, onMounted, ref } from "vue";

export default defineComponent({
  name: "Footer",
  setup() {
    const isDarkMode = ref(false);
    const currentYear = new Date().getFullYear();

    const toggleDarkMode = () => {
      isDarkMode.value = !isDarkMode.value;
      document.body.classList.toggle("dark-mode", isDarkMode.value);
      localStorage.setItem("darkMode", String(isDarkMode.value));
    };

    onMounted(() => {
      const savedDarkMode = localStorage.getItem("darkMode") === "true";
      isDarkMode.value = savedDarkMode;
      document.body.classList.toggle("dark-mode", savedDarkMode);
    });

    return { isDarkMode, currentYear, toggleDarkMode };
  },
});
</script>

<style scoped>
footer {
  background: #1a1a2e;
  color: white;
  padding: 2rem 0;
  text-align: center;
}

.footer-content {
  max-width: 1200px;
  margin: 0 auto;
  padding: 0 20px;
}

.footer-links {
  margin-bottom: 1.5rem;
}

.footer-links a {
  color: #ff8c42;
  margin: 0 15px;
  font-size: 1.1rem;
  text-decoration: none;
  transition: color 0.3s ease;
}

.footer-links a:hover {
  color: #3498db;
}

.dark-mode-container {
  margin: 1.5rem 0;
}

.dark-mode-toggle {
  background: rgba(255, 140, 66, 0.2);
  border: 2px solid rgba(255, 140, 66, 0.3);
  border-radius: 50%;
  width: 50px;
  height: 50px;
  font-size: 1.3rem;
  cursor: pointer;
  transition: all 0.3s ease;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  color: #ff8c42;
}

.dark-mode-toggle:hover {
  background: rgba(255, 140, 66, 0.4);
  transform: scale(1.1);
}

.copyright {
  font-size: 0.9rem;
  opacity: 0.8;
}
</style>
