// src/components/Header.tsx
import { useState } from "react";

function Header() {
  const [mobileOpen, setMobileOpen] = useState(false);

  const closeMenu = () => {
    setMobileOpen(false);
  };

  return (
    <header>
      <nav className="container">
        <div className="logo">🕺🏽Salsa Segura</div>
        <ul className={`nav-links ${mobileOpen ? "active" : ""}`}>
          <li>
            <a href="#home" onClick={closeMenu}>
              Home
            </a>
          </li>
          <li>
            <a href="#events" onClick={closeMenu}>
              Events
            </a>
          </li>
          <li>
            <a href="#lessons" onClick={closeMenu}>
              Lessons
            </a>
          </li>
          <li>
            <a href="#instructor" onClick={closeMenu}>
              Instructor
            </a>
          </li>
          <li>
            <a href="#contact" onClick={closeMenu}>
              Contact
            </a>
          </li>
        </ul>
        <button
          className="hamburger"
          onClick={() => setMobileOpen(!mobileOpen)}
          aria-expanded={mobileOpen}
          aria-label="Toggle menu"
        >
          <span></span>
          <span></span>
          <span></span>
        </button>
      </nav>
    </header>
  );
}

export default Header;

// src/components/Header.vue
<template>
  <header>
    <nav class="container">
      <div class="logo">🕺🏽Salsa Segura</div>
      <ul :class="['nav-links', { active: mobileOpen }]">
        <li><a href="#home" @click="closeMenu">Home</a></li>
        <li><a href="#events" @click="closeMenu">Events</a></li>
        <li><a href="#lessons" @click="closeMenu">Lessons</a></li>
        <li><a href="#instructor" @click="closeMenu">Instructor</a></li>
        <li><a href="#contact" @click="closeMenu">Contact</a></li>
      </ul>
      <button class="hamburger" @click="mobileOpen = !mobileOpen" :aria-expanded="mobileOpen" aria-label="Toggle menu">
        <span></span><span></span><span></span>
      </button>
    </nav>
  </header>
</template>

<script lang="ts">
import { defineComponent, ref } from "vue";

export default defineComponent({
  setup() {
    const mobileOpen = ref(false);
    
    const closeMenu = () => {
      mobileOpen.value = false;
    };
    
    return { mobileOpen, closeMenu };
  },
});
</script>

<style scoped>
/* Keep actual styling in the global stylesheet (root style.css) */
.hamburger {
  background: none;
  border: none;
  padding: 0;
}
</style>
