// src/components/WorkInProgress.tsx
import "./WorkInProgress.css";

function WorkInProgress() {
  return (
    <div className="wip-container">
      <div className="content">
        <h1 className="font-great-vibes">Salsa Segura</h1>
        <h2>Work in Progress</h2>
        <p>
          We are currently working on our new website to bring you the best
          dance experience.
        </p>
        <p>Stay tuned for updates!</p>
        <div className="contact-info">
          <p>In the meantime, feel free to contact us:</p>
          <a href="mailto:info@salsasegura.com">info@salsasegura.com</a>
          <br />
          <a
            href="https://www.instagram.com/SalsaSegura"
            target="_blank"
            rel="noopener noreferrer"
          >
            @SalsaSegura
          </a>
        </div>
      </div>
    </div>
  );
}

export default WorkInProgress;

// src/components/WorkInProgress.vue
<template>
  <div class="wip-container">
    <div class="content">
      <h1 class="font-great-vibes">Salsa Segura</h1>
      <h2>Work in Progress</h2>
      <p>We are currently working on our new website to bring you the best dance experience.</p>
      <p>Stay tuned for updates!</p>
      <div class="contact-info">
        <p>In the meantime, feel free to contact us:</p>
        <a href="mailto:info@salsasegura.com">info@salsasegura.com</a>
        <br>
        <a href="https://www.instagram.com/SalsaSegura" target="_blank" rel="noopener noreferrer">@SalsaSegura</a>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';

export default defineComponent({
  name: 'WorkInProgress',
});
</script>

<style scoped>
.wip-container {
  display: flex;
  justify-content: center;
  align-items: center;
  min-height: 100vh;
  background: linear-gradient(135deg, #ff8c42 0%, #3498db 100%);
  color: white;
  text-align: center;
  padding: 20px;
}

.content {
  background: rgba(255, 255, 255, 0.1);
  backdrop-filter: blur(10px);
  padding: 3rem;
  border-radius: 1rem;
  box-shadow: 0 4px 30px rgba(0, 0, 0, 0.1);
  border: 1px solid rgba(255, 255, 255, 0.3);
  max-width: 600px;
}

h1 {
  font-family: 'Great Vibes', cursive;
  font-size: 4rem;
  margin-bottom: 1rem;
  text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.3);
}

h2 {
  font-size: 2rem;
  margin-bottom: 1.5rem;
  font-weight: 300;
}

p {
  font-size: 1.2rem;
  margin-bottom: 1rem;
  line-height: 1.6;
}

.contact-info {
  margin-top: 2rem;
  padding-top: 2rem;
  border-top: 1px solid rgba(255, 255, 255, 0.3);
}

a {
  color: white;
  text-decoration: none;
  font-weight: bold;
  font-size: 1.2rem;
  transition: opacity 0.3s;
  display: inline-block;
  margin: 0.5rem 0;
}

a:hover {
  opacity: 0.8;
  text-decoration: underline;
}

@media (max-width: 768px) {
  h1 {
    font-size: 3rem;
  }

  h2 {
    font-size: 1.5rem;
  }

  .content {
    padding: 2rem 1rem;
  }
}
</style>
